version: '3'
services:
  db:
    container_name: sql_new
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: son
      MYSQL_PASSWORD: son
    ports:
      - "3306:3306"
    networks:
      - backend
  apps:
    container_name: my_apps
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/app/golang_fiber
    networks:
      - backend
    depends_on:
      - db
networks:
  backend:
  
